### ISSUE TITLE
Set focus at the text line

### ISSUE THREAD

**Issue by MaxMVP** [JoseTomasTocino/QuickBookmarkToFolder#10]
Feature Request: Set focus at the text line on clicking the addon button.

**Comment by redtif** [comment]
Support request

**Comment by JoseTomasTocino** [comment]
This feature is something that was coded from the very beginning and in fact it works for me in the development version. Could you guys tell me your testing environment? Operating system and firefox version at least. Thanks!

**Comment by Fixer-007** [comment]
Firefox 58.0.2 on Windows 7 sp1

**Comment by redtif** [comment]
Firefox 58.0.2 64bit on Windows 10 pro 1709

**Comment by MaxMVP** [comment]
Firefox 58.0.2 64bit @ Windows 10 Pro 1709
(focus never worked for me since FF57)

**Comment by JoseTomasTocino** [comment]
Thanks guys. Looks like there's a bug in Firefox that blocks the focus on the popup, but it's been fixed in Firefox 60. You can read about it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1324255

I've just tested the extension in Firefox Nightly 60 and it works just as expected.

**Comment by Fixer-007** [comment]
This reminds me of "But the princess is in another castle" for some reason, glad it is fixed :D
