### ISSUE TITLE
Icon Lost in Addon Manager

### ISSUE THREAD

**Issue by Rictusempra** [JoseTomasTocino/QuickBookmarkToFolder#6]
![image](https://user-images.githubusercontent.com/16912240/33920456-0f414fca-dff9-11e7-9b76-95d8bfaa0510.png)

Is this as design?

**Comment by JoseTomasTocino** [comment]
Nope, it's not as design. Thanks for reporting the bug.

**Comment by JoseTomasTocino** [comment]
Fixed in 0.0.7
