### ISSUE TITLE
Firefox 57: visual text corruption for scrolling big lists

### ISSUE THREAD

**Issue by Fixer-007** [JoseTomasTocino/QuickBookmarkToFolder#8]
When your search gives a big list - you need to scroll it, so scrolling gives text corruption, it is pretty much initial text with scrolled over text on top visual bug.

**Comment by JoseTomasTocino** [comment]
@Fixer-007 could you upload a screenshot of the problem you described?

**Comment by Fixer-007** [comment]
Example screenshot, to reproduce, create 20-30 bookmark folders, then type some frequent latter, like a
![default](https://user-images.githubusercontent.com/16494741/36763463-b916575c-1c30-11e8-8041-478a1b3ef07a.png)

Firefox 58.0.2 / Win7

**Comment by JoseTomasTocino** [comment]
This is fixed in the 0.1.0 release.
